재수성.yml

diff --git a/.github/workflows/CD.yml b/.github/workflows/CD.yml
--- a/.github/workflows/CD.yml
+++ b/.github/workflows/CD.yml
@@ -1,54 +1,62 @@
-name: CD (Continuous Deploy)
+name: Django CD (Continuous Deploy)
 
 on:
   repository_dispatch:
-    types: [FRONTEND_TEST_FINISH_TRIGGER]
+    types: [BACKEND_TEST_FINISH_TRIGGER]
 
 jobs:
   build:
-    name: Build and Push Docker Image
+    name: build-app
     runs-on: ubuntu-latest
-
     steps:
     - name: Checkout repository
       uses: actions/checkout@v3
 
-    - name: Set up Node.js
-      uses: actions/setup-node@v2
+    - name: Set up Python
+      uses: actions/setup-python@v2
       with:
-        node-version: '20'
+        python-version: 3.10.5
 
-    # 의존성 캐싱
-    - name: Cache node_modules
+    - name: Cache pip
       uses: actions/cache@v3
       with:
-        path: '**/node_modules'
-        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
+        path: ~/.cache/pip
+        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
         restore-keys: |
-          ${{ runner.os }}-node-
+          ${{ runner.os }}-pip-
 
     - name: Install dependencies
-      if: steps.cache.outputs.cache-hit != 'true'
-      run: npm install
-
-    - name: Create .env.production for Docker Build
+      working-directory: ./si_follow
       run: |
-        echo "${{ secrets.ENV_PRODUCTION }}" > .env.production
+        if [ -f requirements.txt ]; then
+          python -m venv .venv
+          source .venv/bin/activate
+          pip install --upgrade pip
+          pip install -r requirements.txt
+        else
+          echo "requirements.txt not found. Exiting."
+          exit 1
+        fi
 
-    - name: Build Next.js app
-      run: npm run build
+    - name: Grant execute permission for scripts
+      run: |
+        chmod +x si_follow/wait-for-it.sh
+        chmod +x si_follow/manage.py
 
     - name: Configure Docker
       uses: docker/setup-buildx-action@v1
 
-    # Docker 이미지 캐싱 설정
-    - name: Cache Docker layers
-      uses: actions/cache@v3
+    - name: Cache Docker Layers
+      uses: actions/cache@v2
       with:
         path: /tmp/.buildx-cache
-        key: ${{ runner.os }}-buildx-${{ github.sha }}
+        key: ${{ runner.os }}-buildx-${{ env.VERSION }}
         restore-keys: |
           ${{ runner.os }}-buildx-
+
+    - name: Set up Docker BuildKit
+      run: |
+        echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV
 
     - name: Login to GHCR
       uses: docker/login-action@v1
@@ -57,52 +65,52 @@ jobs:
         username: ${{ github.actor }}
         password: ${{ secrets.GHCR_TOKEN }}
 
-    - name: Set GITHUB_USERNAME environment variable
-      run: echo "GITHUB_USERNAME=${{ github.actor }}" >> $GITHUB_ENV
-
-    - name: Add Github Actions IP to Security group
-      continue-on-error: true
+    - name: Build and push Docker image
       run: |
-        aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
-
-    # Docker 빌드와 푸시에 캐시 사용
-    - name: Build and Push Docker image
-      run: |
-        docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache \
-                            --cache-to=type=local,dest=/tmp/.buildx-cache-new \
-                            --platform linux/arm64 \
-                            -f Dockerfile \
-                            -t ghcr.io/${{ github.actor }}/nextjs-app:latest \
-                            --push .
+        cd si_follow
+        docker buildx build --platform linux/arm64 -f Dockerfile -t ghcr.io/${{ github.actor }}/si-follow-django-server:latest --push .
 
   deploy:
     needs: build
-    name: Deploy to AWS EC2
-    runs-on: [ self-hosted, deploy-si-follow-frontend ]
+    name: Deploy
+    runs-on: [self-hosted, deploy-si-backend]
     steps:
 
-    - name: Get GitHub Actions IP
+    - name: Get Github Actions IP
       id: ip
-      uses: haythem/public-ip@v1.3
-  
-    - name: Configure AWS Credentials
-      uses: aws-actions/configure-aws-credentials@v2
+      uses: haythem/public-ip@v1.2
+
+    - name: Configure AWS IAM Credentials
+      uses: aws-actions/configure-aws-credentials@v3
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ap-northeast-2
 
+    - name: Remove existing Github Actions IP from Security Group
+      run: |
+        aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32 || true
+
+    - name: Add Github Actions IP to Security Group
+      run: |
+        aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
+
+    - name: Login to GHCR
+      uses: docker/login-action@v1
+      with:
+        registry: ghcr.io
+        username: ${{ github.actor }}
+        password: ${{ secrets.GHCR_TOKEN }}
+
     - name: Deploy to production
       uses: appleboy/ssh-action@v0.1.10
       with:
-        host: ${{ secrets.HOST_PROD }}
+        host: ${{ secrets.HOST_IP }}
         username: ec2-user
         key: ${{ secrets.PRIVATE_KEY }}
         script_stop: true
         script: |
-          cd /home/ec2-user/si-follow/react-frontend
-
-          export GITHUB_USERNAME=${{ github.actor }}
+          cd /home/ec2-user/si-follow/django-backend
           
           docker-compose down
           echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
